# Use root/example as user/password credentials
version: "3.8"

services:
  server:
    entrypoint:
    - sleep
    - infinity
    image: node:latest
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    # build:
    #  context: myapp
    restart: always
    
    container_name: server4
    ports:
    - 3000:3000
    environment:
      MONGODB_CONNSTRING: mongodb://root:example@mongodb:27017
    depends_on:
      - mongodb
    networks: 
      - mongo1_network

  mongodb:
    image: mongo:7.0-rc-jammy
    restart: always
    container_name: mongodb4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: local_library
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks: 
      - mongo1_network
    ports: 
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo-express4
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root          #| ''              | mongo-express web username
      ME_CONFIG_BASICAUTH_PASSWORD: example       #| ''              | mongo-express web password
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true        #| 'true'          | Enable admin access to all databases. Send strings: `"true"` or `"false"`
      ME_CONFIG_MONGODB_ADMINUSERNAME: root       #| ''              | MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: example    #| ''              | MongoDB admin password
      ME_CONFIG_MONGODB_PORT: 27017               #| 27017           | MongoDB port
      ME_CONFIG_MONGODB_SERVER: mongodb           #| 'mongo'         | MongoDB container name. Use comma delimited list of host names for replica sets.
      ME_CONFIG_OPTIONS_EDITORTHEME: default      #| 'default'       | mongo-express editor color theme, [more here](http://codemirror.net/demo/theme.html)
      ME_CONFIG_REQUEST_SIZE: 100kb               #| '100kb'         | Maximum payload size. CRUD operations above this size will fail in [body-parser](https://www.npmjs.com/package/body-parser).
      ME_CONFIG_SITE_BASEURL: /                   #| '/'             | Set the baseUrl to ease mounting at a subdirectory. Remember to include a leading and trailing slash.
      ME_CONFIG_SITE_COOKIESECRET: cookiesecret   #| 'cookiesecret'  | String used by [cookie-parser middleware](https://www.npmjs.com/package/cookie-parser) to sign cookies.
      ME_CONFIG_SITE_SESSIONSECRET: sessionsecret #| 'sessionsecret' | String used to sign the session ID cookie by [express-session middleware](https://www.npmjs.com/package/express-session).
      ME_CONFIG_SITE_SSL_ENABLED: false           #| 'false'         | Enable SSL.
      ME_CONFIG_SITE_SSL_CRT_PATH:                #| ''              | SSL certificate file.
      ME_CONFIG_SITE_SSL_KEY_PATH:                #| ''              | SSL key file.

      MONGODB_CONNSTRING: mongodb://root:example@mongodb:27017/

    networks: 
      - mongo1_network 
  
    depends_on:
      - mongodb

networks:
  mongo1_network:
    driver: bridge